/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author USUARIO
 */
public class Interfaz1 extends javax.swing.JFrame {
    private Object JText_ME_Direccion;
    private Object JLabel_ME_Imagen;
    private Object ObjStaticMaps;
    private Object JText_ME_Zoom;
    private Object JText_ME_Escala;

    /**
     * Creates new form Interfaz
     */
    public Interfaz1() {
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0, 0, 1320, 760, 30, 30); 
        AWTUtilities.setWindowShape(this, forma);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SALIR = new javax.swing.JToggleButton();
        ingresar = new javax.swing.JToggleButton();
        textoInicio = new javax.swing.JLabel();
        FONDO1 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIR.setBackground(new java.awt.Color(204, 204, 204));
        SALIR.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 680, 140, 50));

        ingresar.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        ingresar.setText("ENTRAR");
        ingresar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ingresarComponentAdded(evt);
            }
        });
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, 140, 50));

        textoInicio.setBackground(new java.awt.Color(102, 255, 255));
        textoInicio.setFont(new java.awt.Font("AR HERMANN", 2, 120)); // NOI18N
        textoInicio.setText("Magic Route");
        getContentPane().add(textoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 780, 160));

        FONDO1.setFont(new java.awt.Font("AR CHRISTY", 0, 11)); // NOI18N
        FONDO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuenca.jpg"))); // NOI18N
        FONDO1.setText("jLabel1");
        FONDO1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                FONDO1ComponentAdded(evt);
            }
        });
        getContentPane().add(FONDO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1300, 740));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos-gris-este-fondo-de-pantalla-llamado-esta-archivado-en-la-s-categoria-1025187.jpg"))); // NOI18N
        fondo1.setText("jLabel1");
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
     
    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        try {
            prueba1 panel = new prueba1();
            panel.setVisible(true);
            
            this.setVisible(false);
            //this.crearMapa();
        } catch (Exception ex) {
        }
        
    }//GEN-LAST:event_ingresarActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void FONDO1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_FONDO1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_FONDO1ComponentAdded

    private void ingresarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ingresarComponentAdded
              // TODO add your handling code here:
        try {
            prueba1 panel = new prueba1();
            panel.setVisible(true);
            this.setVisible(false);
            //this.crearMapa();
        } catch (Exception ex) {
        }
        
    }//GEN-LAST:event_ingresarComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO1;
    private javax.swing.JToggleButton SALIR;
    private javax.swing.JLabel fondo1;
    private javax.swing.JToggleButton ingresar;
    private javax.swing.JLabel textoInicio;
    // End of variables declaration//GEN-END:variables
}
